apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kraftcontroller
  namespace: confluent
spec:
  replicas: 1
  dataVolumeCapacity: 1Gi
  image:
    application: confluentinc/cp-server:7.9.0
    init: confluentinc/confluent-for-kubernetes:2.9.0